function proteomovie(data_directory, movie_file, n_randomised_trees, options)

% proteomovie(organism, data_directory, movie_file, n_randomised_trees)
%
% generate proteomovie from files prepared by proteomovie-prepare-files.py
%
% wrapper function for running 
%   proteomap_colormap      (generate colormap file)
%   protein_abundance       (generate protein abundance files)
%   proteomap_treemap_movie (generate movie file)
%
% data_directory:     contains the files and subdirectories generated by the python proteomaps pipeline
%                     (including the file filenames.csv)
% movie_file:         path and filename (without extension!) of the movie file to be written
%                     (additional graphics will be written to the same directory)
% n_randomised_trees: same number as chosen in the python proteomaps pipeline
% options:            struct for further options (for details, see "help 'proteomap_treemap_movie')

eval(default('options','struct'));

ca;

% --------------------------------------
% read sample names in the data set 
  
T = load_any_table([data_directory '/filenames.csv']);
[data_directory '/filenames.csv']
organism       = T{1,1};
show_data_sets = strrep(T(:,3),'_',' ');

% % --------------------------------------
% % split movie_file into movie_directory and movie_file
% 
% dum = strsplit(movie_file,filesep);
% if length(dum)>1,
%   movie_directory = [ strjoin(dum(1:end-1),filesep) filesep];
%   movie_file  = dum{end};
% else
%   movie_directory = ['.' filesep];
% end

options.show_black_frames = 2;
options.output_directory  = [];
options.show_data_sets    = show_data_sets;

% --------------------------------------

pathnames = proteomaps_path_names(data_directory);

proteomap_colormap(data_directory, pathnames, 0);

protein_abundance(data_directory, n_randomised_trees, pathnames, 0);

proteomap_treemap_movie(organism, data_directory, movie_file, options);
