function proteomovie(data_directory, movie_name, n_randomised_trees)

%proteomovie(organism, data_directory, movie_name, n_randomised_trees)
%
%wrapper function for generating proteomovies 
%
%data_directory: contains the files and subdirectories generated by the python proteomaps pipeline
%                (including the file filenames.csv)
%movie_name:     path and filename of the movie file to be written
%                (additional graphics will be written to the same directory)
%n_randomised_trees: same number as chosen in the python proteomaps pipeline
  
% --------------------------------------
% read sample names in the data set 
  
T = load_any_table([data_directory '/filenames.csv']);

organism       = T{1,1};
show_data_sets = strrep(T(:,3),'_',' ');


% --------------------------------------
% split movie_name into movie_directory and movie_name

dum = strsplit(movie_name,filesep);
if length(dum)>1,
  movie_directory =  [ strjoin(dum(1:end-1),filesep) filesep];
  movie_name =  dum{end};
else
  movie_directory = ['.' filesep];
end

graphics_directory = movie_directory;


% --------------------------------------

pathnames = proteomaps_path_names(data_directory);

protein_abundance(data_directory, n_randomised_trees, pathnames);

show_protein_colormap(data_directory, pathnames);

options                   = struct;
options.show_black_frames = 0;
options.output_directory  = movie_directory;
options.show_data_sets    = show_data_sets;

proteomap_treemap_movie(organism, data_directory, movie_name, options);
